### ISSUE TITLE
Replace callbacks by ES6 Promises

### ISSUE THREAD

**Issue by kazzkiq** [caravel-tool/caravel#10]
There are some pieces of code which started to fall into the [callback hell](http://callbackhell.com/) hole.

Instead of solving this with solutions such as modularizing each piece of code, I'm willing to make use of ES6 Iterators/Generators to make the code more readable.

So this (simple case, there are worse samples on [`Caravel.js`](https://github.com/caravel-tool/caravel/blob/master/bin/Caravel.js) file):

``` js
installDependenciesAndBuildAndWatch (self) {
    DataLogger.insertLog('running')
    self.isRunning = true
    self.installDependencies(() => {
      self.build(() => {
        self.watch(self)
      })
    })
  }
```

Could turn into something like this:

``` js
* installDependenciesAndBuildAndWatch () {
    DataLogger.insertLog('running')
    this.isRunning = true

    yield this.installDependencies()
    yield this.build()
    yield this.watch(this)
  }
```

**Comment by kazzkiq** [comment]
Will be using Promises instead.

**Comment by lflimeira** [comment]
Is it possible to use async-await instead?

**Comment by kazzkiq** [comment]
Yes it is! At the time of this issue, async/await was still cutting-edge in Node, but now it would make lots of sense.

**Comment by mflobo** [comment]
is this up for grabs? i'd like to start working on it.

**Comment by kazzkiq** [comment]
@mflobo I'm actually going to refactor Caravel as a whole. And help would be welcome!

This issue will eventually be closed because of the refactoring but if you want to help, please stay around and watch the project. You may see some movement soon.

**Comment by mflobo** [comment]
cool, i'll keep an eye out.

**Comment by kazzkiq** [comment]
Closing this since the code is being ported to [Crystal](https://github.com/crystal-lang/crystal).
