### ISSUE TITLE
Enable watch without re-installing dependencies

### ISSUE THREAD

**Issue by kazzkiq** [caravel-tool/caravel#3]
Today every time Caravel detects a change on a repository, the following steps are made:
1. Clone repo again;
2. **Re-install npm dependencies all over; (sloooow)**
3. Run tasks defined on `caravel.json`;
4. Deploy app.

The second step generally take a lot of time, and not all changes need npm dependencies reinstalled. So a better approach would be running `npm install` **only if needed** (only when changes into `package.json` are detected).

**Comment by kazzkiq** [comment]
Using this approach to solve the Issue:
1. If hash from `package.json` is the same from last commit and if `node_modules/` folder exists;
2. Then skip `npm install` command.

Otherwise, if `package.json` has any changes or if `node_modules/` folder isn't found, run `npm install` again.

This approach can still lead to issues if, for example, a single dependency gets manually deleted from `node_modules/` path. In this case Caravel would not detect this and would not re-run `npm install`, which would probably lead to build breaks (Caravel would still handle this, preventing the publication of the failed build into production).

But as the above example would only happen if a silly dev deliberated screwed things up in his own production server, I think its safe enough to implement this approach this way.

**Comment by felipeuntill** [comment]
Run the `npm install`is a important step and put this functionality inside caravel is a bad idea, recycle the entire project and run install against can be slow but is normal.
Keep caravel clever 👍

**Comment by kazzkiq** [comment]
I agree that this approach can be hazardous, however it is not uncommon to find projects falling into [dependency hell](http://www.haneycodes.net/npm-left-pad-have-we-forgotten-how-to-program/) today. Caravel itself uses Express which relies on **22 dependencies** in order to start working.

Now imagine a big project with lots of dependencies where you just want to fix a tiny typo on your webpage. Re-running `npm install` in these cases could be a nightmare, and would be consuming precious resources (disk/processing/bandwidth) from your production server.

I  think the best approach would be a middle ground. Caravel should re-run `npm install` by default, but should give users an option to when they want to avoid running it.

So, if user runs:

``` bash
caravel watch --port 5005
```

Caravel delete `node_modules` and re-install dependencies (`npm install`).

But if a flag is explicity specified:

``` bash
caravel watch --port 5005 --keep-dependencies
```

Caravel will then keep dependencies and try to build the project without running `npm install` again.

**Comment by kazzkiq** [comment]
Now users can prevent `npm install` with flags `-n` or `--no-install`. Example:

```
caravel build -n
```

```
caravel watch --no-install
```

This is useful when an user is sure there is no need to re-install packages. Also useful if a project has no package.json file (non-Node, for example) and user still want to use Caravel for deployment.
